### ISSUE TITLE
package wrong(java)

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#1]
All the packages can't work normally.
For example:
`package cn.edu.sustech.cs307.dto.prerequisite;`

If change the package to `package main.java.cn.edu.sustech.cs307.dto.prerequisite;` It will be ok.

I wonder how to solve this problem. I think changing all the packages is not so good.....

**Comment by NewbieOrange** [comment]
Please import this project as a maven project. main and java is not part of the package.

**Comment by NewbieOrange** [comment]
Note that when cloning project using Intellij IDEA, select "Trust Mode" for maven.

You should also be able to get maven working by right-clicking on the project in project window, and choose "Add Framework Support", then choose Maven.

**Comment by xbdeng** [comment]
Thank you for your explanation!

Sorry, I can't find maven after I click the "Add Framework Support"

![image](https://user-images.githubusercontent.com/56679342/116784657-fa54b000-aac7-11eb-813e-8f1d29176736.png)


There is still something wrong like this.

![image](https://user-images.githubusercontent.com/56679342/116784642-e01ad200-aac7-11eb-9124-b4bc2648e692.png)

**Comment by NewbieOrange** [comment]
You may open pom.xml and see if there is a `trust project` button.
![trust project](https://user-images.githubusercontent.com/7200314/116784887-3f2d1680-aac9-11eb-94ea-8a578f9b801a.png)

**Comment by xbdeng** [comment]
Sorry, I haven't seen this button all the time. 

But when I clone the project, I choose a trust bottom like this.
![image](https://user-images.githubusercontent.com/56679342/116785022-fa55af80-aac9-11eb-8ccd-a0579dd4fd0e.png)

**Comment by NewbieOrange** [comment]
After trust and syncing the maven project, it still does not work? Does maven gives any error message?

**Comment by xbdeng** [comment]
Yes, there are many errors

![image](https://user-images.githubusercontent.com/56679342/116786713-c03cdb80-aad2-11eb-8b44-1ebcf3a6d1e4.png)

**Comment by xbdeng** [comment]
Thank you for your patience!

I have solved this problem successfully!

Good night!

**Comment by NewbieOrange** [comment]
@xbdeng consider putting your solution here for other students having same problem. :)

**Comment by xbdeng** [comment]
1. Change the JDK to  edition 16
2. [Maven: Failed to read artifact descriptor](https://stackoverflow.com/questions/6642146/maven-failed-to-read-artifact-descriptor)
3. [解决Cannot resolve plugin org.apache.maven.plugins:maven-site-plugin:3.3问题](https://blog.csdn.net/panshi5188/article/details/102977547)
