### ISSUE TITLE
导入用户过程中程序无响应

### ISSUE THREAD

**Issue by yundaqwe** [NewbieOrange/SUSTech-SQL-Project2-Public#100]
在添加用户时(调用importer.importUsers方法过程中)，大约添加到8000多条后，程序就会被莫名其妙的阻塞，也没有错误发生，请问可能是什么原因。
![image](https://user-images.githubusercontent.com/54757996/120878304-0b746d80-c5ee-11eb-99db-4422eb2b7c4d.png)

**Comment by NewbieOrange** [comment]
可以开debug看看是卡在哪儿了

**Comment by NewbieOrange** [comment]
问题解决了吗？

**Comment by yundaqwe** [comment]
> 问题解决了吗？

已经解决，我在导入数据的方法前加上了synchronized关键字，现在可以了
