### ISSUE TITLE
关于searchCourse的测试数据的疑问

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#101]
请问这条测试用例里面，为什么字典序大的MA102a反而排在字典序小的MA102B之前？
![QQ截图20210605121443](https://user-images.githubusercontent.com/64548919/120879735-1207e280-c5f8-11eb-940c-20aad62cf4f5.jpg)

**Comment by NewbieOrange** [comment]
![图片](https://user-images.githubusercontent.com/7200314/120880083-ac692580-c5fa-11eb-98b2-4538186c6206.png)

**Comment by YeeTone** [comment]
但是按照ASCII码的字典顺序，'B'的数值的66，而'a'的数值是97。按照ASCII字典顺序的话，应该MA102a排在后面？

**Comment by NewbieOrange** [comment]
> 
> 
> 但是按照ASCII码的字典顺序，'B'的数值的66，而'a'的数值是97。按照ASCII字典顺序的话，应该MA102a排在后面？

不好意思，看错了。顺序请以数据库order by的顺序为准。

![图片](https://user-images.githubusercontent.com/7200314/120883102-e42d9880-c60d-11eb-885d-392b480e29c3.png)
