### ISSUE TITLE
关于semester与enrollCourse的几个疑问

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#102]
1.问一下import semester的时候，是默认按照时间顺序插入吗
2.用EnrollCourse这个方法登记的课程都会是当前学期（也就是date最晚的学期）的吗？而getCourseTable则默认返回这个学期的课程表？还是说即使有了新学期也还是可以给学生enroll旧学期的CourseSection，而getCourseTable面向的是所有学期？

**Comment by NewbieOrange** [comment]
> 问一下import semester的时候，是默认按照时间顺序插入吗

不是

> 用EnrollCourse这个方法登记的课程都会是当前学期（也就是date最晚的学期）的吗？

不是

> 还是说即使有了新学期也还是可以给学生enroll旧学期的CourseSection，而getCourseTable面向的是所有学期？

是的，根据course table传入的日期确定学期，我们保证学期不会重叠。
