### ISSUE TITLE
关于test enroll course 2的数据疑问

### ISSUE THREAD

**Issue by YG-yyds** [NewbieOrange/SUSTech-SQL-Project2-Public#103]
这学生在本学期选这个courseId的别的课，然后挂科了有成绩
然后准备选这门课的别的section
expect是success

![1](https://user-images.githubusercontent.com/75725759/120882113-32d83400-c608-11eb-90e4-8d5c877abc22.png)
![2](https://user-images.githubusercontent.com/75725759/120882122-38ce1500-c608-11eb-95b3-3439e1d6bd5d.png)
![3](https://user-images.githubusercontent.com/75725759/120882124-3bc90580-c608-11eb-9b4a-b5f5d52a9316.jpg)

求问这种情况应该返回什么结果，我返回的是course conflict found

**Comment by NewbieOrange** [comment]
应该返回`SUCCESS`，`COURSE_CONFLICT_FOUND`仅限同一学期课程间，否则学生无法重修挂科课程。

**Comment by NewbieOrange** [comment]
这是哪个样例，是在enrollCourse1还是2？

**Comment by YG-yyds** [comment]
test2里边的，学期2有grade（中间添加过grade）


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NewbieOrange/SUSTech-SQL-Project2-Public] 关于test enroll course 2的数据疑问 (#103)




 
这是哪个样例，是在enrollCourse1还是2？
 
&mdash;

**Comment by NewbieOrange** [comment]
已修复，请检查。

**Comment by YG-yyds** [comment]
已经测试过OK了ｸﾞｯ!(๑&bull;̀ㅂ&bull;́)و✧


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NewbieOrange/SUSTech-SQL-Project2-Public] 关于test enroll course 2的数据疑问 (#103)




 
已修复，请检查。
 
&mdash;
