### ISSUE TITLE
Exception problem

### ISSUE THREAD

**Issue by dreamking60** [NewbieOrange/SUSTech-SQL-Project2-Public#106]
throw了EntityNotFound等exception之后程序是不是不应该终止，我们要自己catch这个exception然后继续运行

**Comment by NewbieOrange** [comment]
是的，不过目前输出不应抛出该异常。

**Comment by Zhou-Yicheng** [comment]
异常要么抛出要么捕获，无法既抛出又捕获。

**Comment by dreamking60** [comment]
> 是的，不过目前输出不应抛出该异常。



> 异常要么抛出要么捕获，无法既抛出又捕获。

额。。
