### ISSUE TITLE
semester' begin and end shouldn't  have intersection

### ISSUE THREAD

**Issue by SpaceIshtar** [NewbieOrange/SUSTech-SQL-Project2-Public#107]
问题一：
in sample semester:
one semester begin 2019-07-01 and end   2019-09-14
another semester begin 2019-02-04 and  end 2019-07-14
These two  semesters have intersections.
那这样如果不同学期同一天就会奇怪的有不同的课。
这样一个学期的最后几周和下一个学期的前几周的上不同的课程怎么办？

**Comment by SpaceIshtar** [comment]
one semester begin 2019-07-01 and end 2019-09-14
another semester begin 2019-02-04 and end 2019-07-14
这个是给的测试数据

**Comment by NewbieOrange** [comment]
稍后修正。

**Comment by NewbieOrange** [comment]
已修正，请检查。
