### ISSUE TITLE
关于#88 数据库编码影响排序结果的疑问

### ISSUE THREAD

**Issue by goalandthink** [NewbieOrange/SUSTech-SQL-Project2-Public#108]
我也出现了同样的问题，但我数据库应该已经使用UTF-8编码了，‘中英’<‘英文’依然是False。
![20210605231507](https://user-images.githubusercontent.com/61463030/120896442-24b00500-c654-11eb-9600-cf3d44dbbd27.png)
![20210605231600](https://user-images.githubusercontent.com/61463030/120896444-2a0d4f80-c654-11eb-81a8-c024e249e9a2.png)
首先可以看到各个数据库的编码都是UTF-8
![20210605231642](https://user-images.githubusercontent.com/61463030/120896452-3a252f00-c654-11eb-8176-aac6af02ac95.png)
但‘中英’<‘英文’依然是False。
真的如#88 所说是UTF-8编码问题吗？

**Comment by NewbieOrange** [comment]
请在创建表时将encoding设置为'UTF8'，lc_collate设置为'en_US.UTF8'。
