### ISSUE TITLE
About method addEnrolledCourseWithGrade()

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#11]
As stated in the ERADME, all add*() methods should return a value representing the id of the new row. However this one does not have any return value. 
Also, is it possible that the provided studentId and sectionId have already existed in the table and the operation is to add the grade for this student, or all the provided studentId and sectionId are new. 
If this student and section already existed in the database, what should be the operation?

**Comment by NewbieOrange** [comment]
> As stated in the ERADME, all add*() methods should return a value representing the id of the new row. However this one does not have any return value.

README did not say that, read the requirements again.

> Also, is it possible that the provided studentId and sectionId have already existed in the table and the operation is to add the grade for this student, or all the provided studentId and sectionId are new.

You may assume the student-section provided does **not** exist in the database.
