### ISSUE TITLE
新数据中的CourseSection没有semesterId=2的

### ISSUE THREAD

**Issue by SpaceIshtar** [NewbieOrange/SUSTech-SQL-Project2-Public#110]
刚刚我下载了新数据并进行了测试，发现导入的CourseSection中没有semester_id=2的。
我在addCourseSection方法中加入输出语句，在输入的semester_id=2时输出course_id和section_name，但什么也没有输出来。
这也导致了后面searchCourse出现和expected不一致的情况。
![20210606131059](https://user-images.githubusercontent.com/73434395/120913340-ff111300-c6c8-11eb-8688-0f1a07917969.png)
是否是数据出了问题呢？

**Comment by NewbieOrange** [comment]
导入和判断的时候semesterId会自动map为你返回的id值，应该没有问题。

请试试新数据？

**Comment by SpaceIshtar** [comment]
> 导入和判断的时候semesterId会自动map为你返回的id值，应该没有问题。
> 
> 请试试新数据？

新数据依然是这样
我输出了addSemester的返回值，能看到能返回3个id，但在addCourseSection时依然没有输出。
这是新数据设计就是这样，还是？
![QQ图片20210606142043](https://user-images.githubusercontent.com/73434395/120914782-dc83f780-c6d2-11eb-9a23-792159f1bca5.png)

**Comment by NewbieOrange** [comment]
请检查你正在用的框架代码是否已经更新到最新。

**Comment by SpaceIshtar** [comment]
> 请检查你正在用的框架代码是否已经更新到最新。

DataImporter和ProjectJudge都是刚刚更新过的，是最新的。
不过新数据的searchCourse，如果输入的semester_id=2，那么expected的size就是0，所以对我searchCourse就没有影响了
![111](https://user-images.githubusercontent.com/73434395/120915221-371e5300-c6d5-11eb-8cb9-2e3b538e122b.png)

**Comment by NewbieOrange** [comment]
semester=2的时候目前还没有课，正常。

**Comment by SpaceIshtar** [comment]
> semester=2的时候目前还没有课，正常。

OK, thanks
