### ISSUE TITLE
Question about `getCourseTable()`

### ISSUE THREAD

**Issue by Zhou-Yicheng** [NewbieOrange/SUSTech-SQL-Project2-Public#112]
When param of `date` is invalid (not in any semester), should we return NULL or throw `EntityNotFoundException`?

**Comment by NewbieOrange** [comment]
Return the course table as normal (but no course inside).

**Comment by Zhou-Yicheng** [comment]
You mean return an empty table?

**Comment by NewbieOrange** [comment]
> 
> 
> You mean return an empty table?

The document required the table to be non-empty (has key from `MONDAY` to `SUNDAY`), but the corresponding values (the lists) can be empty.
