### ISSUE TITLE
ReferenceStudent 中的enrollCourse的问题描述

### ISSUE THREAD

**Issue by ritian-zhao** [NewbieOrange/SUSTech-SQL-Project2-Public#113]
问题一：
enrollcourse 中对于already_enrolled的描述是：The course (of the section) is already passed by the student
所以看的是course_id有无在选（也就是说先看正在选的这个section_id所在的course_id，再正在选的course_id对应的全部section_id，看有无已经选择），而不是section_id直接赋值的判断。但数据判断中看到的是section_id赋值的直接判断
问题二：
如果是section_id直接赋值的判断，那么enrollcourse 时直接enroll 同一个section_id 两次。第二次是判定ALREADY_ENROLLED呢？还是COURSE_CONFLICT_FOUND呢？答案是COURSE_CONFLICT_FOUND，但是我觉得ALREADY_ENROLLED更加贴切

**Comment by NewbieOrange** [comment]
> already_enrolled的描述是：The course (of the section) is already passed by the student

![图片](https://user-images.githubusercontent.com/7200314/120917740-6f2c9280-c6e3-11eb-8170-2a94c6a1c01c.png)


你是不是看串行了。

> 如果是section_id直接赋值的判断，那么enrollcourse 时直接enroll 同一个section_id 两次。第二次是判定ALREADY_ENROLLED呢？还是COURSE_CONFLICT_FOUND呢？答案是COURSE_CONFLICT_FOUND，但是我觉得ALREADY_ENROLLED更加贴切

答案返回的不就是`ALREADY_ENROLLED`吗？

**Comment by ritian-zhao** [comment]
似乎数据中11714884 student_id  选 section_id 72 返回的是COURSE_CONFLICT_FOUND

**Comment by NewbieOrange** [comment]
> 
> 
> 似乎数据中11714884 student_id 选 section_id 72 返回的是COURSE_CONFLICT_FOUND

请下载最新数据

**Comment by ritian-zhao** [comment]
![a](https://user-images.githubusercontent.com/61463030/120919361-c33b7500-c6eb-11eb-9b08-fbec410842ec.png)
可是结果不是这样

**Comment by ritian-zhao** [comment]
https://github.com/ritian-zhao/computer-organization/blob/main/a.png?raw=true
可是结果不是这样子

**Comment by ritian-zhao** [comment]
![a.png](https://github.com/ritian-zhao/computer-organization/blob/main/a.png?raw=true)
可是结果不是这样

**Comment by ritian-zhao** [comment]
是最新的数据

**Comment by NewbieOrange** [comment]
`[11717487,27]`不是enroll 1里的第一条数据吗，预期结果不是`SUCCESS`？

**Comment by ritian-zhao** [comment]
[b.png](https://github.com/ritian-zhao/computer-organization/blob/main/b.png)
section id 为72 ，studentid 为11714884

**Comment by ritian-zhao** [comment]
![b.png](https://github.com/ritian-zhao/computer-organization/blob/main/b.png?raw=true)
section id 为72， student id为11714884

**Comment by NewbieOrange** [comment]
数据里只有这两条：
`[11714884,126]`
`[11714884,146]`
两个section id 不一样，怎么会返回`ALREADY_ENROLLED`

**Comment by ritian-zhao** [comment]
![c.png](https://github.com/ritian-zhao/computer-organization/blob/main/c.png?raw=true)
可是11714884 学生id  选课146出现了两次（amazing值）

**Comment by NewbieOrange** [comment]
应该是因为你的插入课程函数返回结果是线程不安全的。

**Comment by ritian-zhao** [comment]
![bug.png](https://github.com/ritian-zhao/computer-organization/blob/main/bug.png?raw=true)
学长，方法中也添加了synchronized。总体上感觉也没线程不安全。但是还是会出现11714884 选课146两次。

**Comment by ritian-zhao** [comment]
请问下还有什么其他解决办法吗，谢谢

**Comment by ritian-zhao** [comment]
破案了，谢谢，问题找到了
