### ISSUE TITLE
Document error @return of `passedPrerequisitesForCourse(student, course)`

### ISSUE THREAD

**Issue by Zhou-Yicheng** [NewbieOrange/SUSTech-SQL-Project2-Public#115]
>     * @return true if the student has any course score record that is passed (>=60 or PASS), which means he has passed the course.

The method should return true if the @param `student` pass all the courses in the prerequisite of @param `course`, rather than to check whether he has passed the course.

**Comment by NewbieOrange** [comment]
This has been fixed a long time ago, please pull the latest commit.

**Comment by NewbieOrange** [comment]
Fixed.
