### ISSUE TITLE
有关searchcourse的参数问题

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#116]
在searchcourse中，是需要有一个sectionclass同时满足searchCid，searchName，searchInstructor，searchDayOfWeek，searchClassTime，searchClassLocations，才能返回该coursesearchentry还是有几个sectionclass分别满足这几个条件就可以返回该coursesearchentry呢？

**Comment by NewbieOrange** [comment]
同时满足。
