### ISSUE TITLE
Question about time confilct

### ISSUE THREAD

**Issue by 172698691** [NewbieOrange/SUSTech-SQL-Project2-Public#117]
Since the class_start and class_end in courseSectionClass are not 24-hour time, will there be two classes that one starts at 7am and another starts at 7pm? If there are, how should I judge class_start=7 means 7am or 7pm?

**Comment by NewbieOrange** [comment]
Class time is not clock time, for example, in SUSTech we have class time from 1(first class in morning) to 11 (last class in night).

**Comment by Zhou-Yicheng** [comment]
是节的意思 1-2节 3-4节 …… 10-11节

**Comment by 172698691** [comment]
啊不好意思，理解错意思了
