### ISSUE TITLE
Question about data in searchCourse1(searchCourseMixed.json)

### ISSUE THREAD

**Issue by fll02020** [NewbieOrange/SUSTech-SQL-Project2-Public#119]
Why [11710001, 3, None, ']', None, None, None, None, <CourseType.ALL: 1>, False, False, False, False, 10, 3]
can get 10 result? if we set searchCid to be ']' to search, it should get nothing

**Comment by NewbieOrange** [comment]
The fourth argument should be searchCourseName no?
