### ISSUE TITLE
section_id 存在于course_section table 但是section_class table 缺失

### ISSUE THREAD

**Issue by zion302** [NewbieOrange/SUSTech-SQL-Project2-Public#120]
基于最新的data, 运行benchmark, 到searchCourse1这一步，抛出很多异常信息，是section_id不能在section_class表找到。查看了原因，发现是test_add_course中间读入到 section_id = await rcs.add_course_section(...) 返回 67，然后 cls = cscs[f"{ss['id']}"] 得到的cls是空的list, 具体是cscs[153] 也就是这个section_id下面没有任何section_class数据。这个是有意设计的还是遗漏的？
![image](https://user-images.githubusercontent.com/25132775/121056959-56aa9e00-c7f1-11eb-859e-ea454a278978.png)

**Comment by NewbieOrange** [comment]
一个section不一定有class。这种情况正常导入，但是查课时不显示这门课。
