### ISSUE TITLE
searchCourseBasicResult.json 存在time conflict的两个sections

### ISSUE THREAD

**Issue by zion302** [NewbieOrange/SUSTech-SQL-Project2-Public#122]
共有100个cases, 第一个case是包含10个items 的List[CourseSearchEntry], 第4个和第十个section_classes里存在time conflict:
![image](https://user-images.githubusercontent.com/25132775/121201193-e9f1db00-c8a6-11eb-8575-aee9204747c0.png)

 ` * Time conflict is when multiple sections have time-overlapping classes.*` 
这样，至少这部分的比对测试就不会通过？

同时还存在多个sections属于同一个course
`* Course conflict is when multiple sections belong to the same course. `   
 
![image](https://user-images.githubusercontent.com/25132775/121203225-88327080-c8a8-11eb-94cb-b79bbbaa0c6b.png)

**Comment by NewbieOrange** [comment]
你的理解有问题，conflict是指和学生已选的课程冲突，和搜索结果里的课程有什么关系。

你思考一下你用教务系统的时候，是需要过滤掉和你选的课冲突的课，还是要在搜索结果里过滤掉相互冲突的课？

**Comment by zion302** [comment]
> 你的理解有问题，conflict是指和学生已选的课程冲突，和搜索结果里的课程有什么关系。
> 
> 你思考一下你用教务系统的时候，是需要过滤掉和你选的课冲突的课，还是要在搜索结果里过滤掉相互冲突的课？

这样说就清楚了。文档的描述比较模糊，之前也有不少同学问了类似的问题。

` * Course conflict is when multiple sections belong to the same course.   
  * Time conflict is when multiple sections have time-overlapping classes.     
  * Note that a section is both course and time conflicting with itself!`
加个前提： Compared to already enrolled course(section)... 就清楚多了。

**Comment by NewbieOrange** [comment]
已更新相关描述文档。
