### ISSUE TITLE
Questions about the parameters of searchCourse in the test

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#126]
文档里面说 Rule: searchName in "course.name[section.name]"
为什么测试里面会出现“]”的数据？

**Comment by NewbieOrange** [comment]
a in b = b contains a

不是说a in b = a 是 b 这样的格式

**Comment by Ddduanxt** [comment]
所以说可能会出现所有course.name[section.name] 的子串吗

**Comment by NewbieOrange** [comment]
不一定是子串，可能是完全无关的字符串。

**Comment by Ddduanxt** [comment]
那就是说只要输入的信息是course.name[section.name]子串的就可以查到吗，“]”是会查到全部的数据是吗

**Comment by NewbieOrange** [comment]
可以这么理解

**Comment by Ddduanxt** [comment]
好的好的谢谢

**Comment by Zhou-Yicheng** [comment]
这里用正则匹配会出错

**Comment by Ddduanxt** [comment]
所以这究竟是需要怎么判断呢

**Comment by Ddduanxt** [comment]
不太明白所有合法的情况包括什么

**Comment by NewbieOrange** [comment]
> 所以这究竟是需要怎么判断呢

就用字符串判断是否是子串

> 不太明白所有合法的情况包括什么

所有输入都可以是合法的
