### ISSUE TITLE
关于searchCourse方法里的searchInstructor参数

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#129]
Rule: firstName + lastName begins with searchInstructor
     *                                   or firstName + ' ' + lastName begins with searchInstructor
     *                                   or firstName begins with searchInstructor
     *                                   or lastName begins with searchInstructor.
     这个是指传进来的字符串是”searchInstructor“拼上四种不同情况吗？以及四种情况对应是怎么对应的？（第一种对应中文名，第二种英文名，第三种instructor表的lastName为空，第四种firstName为空吗？这样是否意味着instructor里的add方法也要考虑入参为空的情况？）

**Comment by NewbieOrange** [comment]
不是这个意思，上面就是匹配条件字面意思。

**Comment by 1371131436** [comment]
> 不是这个意思，上面就是匹配条件字面意思。

所以原意是什么啊
