### ISSUE TITLE
About the conflict of course selection

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#13]
The EnrollResult contains 8 types of result
```
         /**
         * Enroll success
         */
        SUCCESS,
        /**
         * Cannot found the section
         */
        COURSE_NOT_FOUND,
        /**
         * The section is full
         */
        COURSE_IS_FULL,
        /**
         * The section is already enrolled by the student
         */
        ALREADY_SELECTED,
        /**
         * The course (of the section) is already passed by the student.
         */
        ALREADY_PASSED,
        /**
         * The student misses prerequisites for the course
         */
        PREREQUISITES_NOT_FULFILLED,
        /**
         * The student's enrolled courses has time conflicts with the section
         */
        COURSE_CONFLICT_FOUND,
        /**
         * Other (unknown) errors
         */
        UNKNOWN_ERROR
```
But when checking whether the section(course) has already been selected, `ALREADY_SELECTED` is returned only when the section is the same. That is to say one student can choose different sections without time conflict of the same course when those two sections do not have a grade. For example, that is to say if Discrete Math Chinese section and Discrete Math English section can be chosen simultaneously by students haven't chosen Discrete Math before if the two sections do not have time conflict with each other?

**Comment by NewbieOrange** [comment]
The EnrollResult has been updated, please check the latest version.
