### ISSUE TITLE
关于conflictCourseNames和ignoreConflict的逻辑

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#131]
想问一下，是不是当ignoreConflict为true时，忽略掉和已经Enroll的课程相互冲突的课程，然后返回的CourseSearchEntry中的conflictCourseNames是一个空的list（或者只含它自己？），如果ignoreConflict为false时，则把已经Enroll的课程中和search到的课程冲突的放进conflictCourseNames中？

**Comment by NewbieOrange** [comment]
是的，不过ignoreConflict为true的时候，显然冲突列表恒为空。
