### ISSUE TITLE
benchmark.py 改用asyncio.gather()后运行hang停滞 

### ISSUE THREAD

**Issue by zion302** [NewbieOrange/SUSTech-SQL-Project2-Public#132]
前面import都没有问题，运行到testing search course1就一直停在那边。之前的benchmark.py没有这个问题
Import departments
Import majors
Import users
Import semesters
Import courses
Import major courses
Import time usage: 10.15s
Testing search course 1

**Comment by NewbieOrange** [comment]
请检查你的search course是否异步安全

**Comment by Zhou-Yicheng** [comment]
可能你在search_course里的连接里又请求了新的连接

**Comment by zion302** [comment]
> 可能你在search_course里的连接里又请求了新的连接

只是在开头用 async with self._pool.acquire() as conn acquire了一个连接 conn, 然后使用这个conn 执行sql fetch了几次数据。中间也没有调用其他包含同样的连接请求的method.
还是stuck在这个问题，尝试设 timeout 但是没有用，都能最终都会抛出一个timeouterror exception.

**Comment by zion302** [comment]
我试了下， return await asyncio.gather(*[query_one(q) for q in query[0:4]]) 把query限制在5个以下就没有问题.。问题是我们不能修改benchmark.py

**Comment by NewbieOrange** [comment]
@ziqin 有什么想法吗

**Comment by zion302** [comment]
benchmark是测试机端的，不是学生递交的范围，测试端能否可以选择用gather和不用gather的两种版本。基于同一个版本的benchmark同样可以测试比较同学递交的implementation代码。

**Comment by ziqin** [comment]
我不太能确定，但感觉像是连接池的连接用完了。

根据[asyncpg文档](https://magicstack.github.io/asyncpg/current/api/index.html#connection-pools)，默认的连接池`max_size`为10；而`asyncio.gather`不限制并发度，并发度遂取决于`query`中元素的数量。

@zion302 可以关注一下 `TimeoutError` 的 stack trace，看看该异常是否从 `self._pool.acquire()` 抛出。

如果确实是这方面的问题，那么，可以考虑调整连接池的大小支持更多的连接，且可以考虑在`self._pool.acquire()`前使用[`asyncio.Semaphore`](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Semaphore)将阻塞转移到无timeout的semaphore身上。从测评的角度看，测评代码可能也要考虑使用限制并发度，但具体限制到多大的并发度是个问题，因为有的同学提交的代码可能确实能支持较高的并发。

**Comment by NewbieOrange** [comment]
我大概明白了，你在acquire的时候不要async with 而是直接await等待试试（记得手动close）？稍后修改评测脚本修正这个问题。

**Comment by NewbieOrange** [comment]
Please try the updated version https://github.com/ziqin/SUSTech-CS307-Project2-Python/commit/3807cae0bfaf229e231758ba3d82dde275987f34 which may address this issue.

**Comment by zion302** [comment]
谢谢各位的帮助。
找到问题根源了。。。在searchCourse代码中间，为了check section(course)是否满足prerequisite调用了 self.passed_prerequisites_for_course 其本身有acquire conn, 这样就造成了nested acquire 结果就是deadlocking。其实之前 @Zhou-Yicheng 同学有提到，当时我没注意到那行调用的代码。
我已经修改了searchCourse的代码，完全没问题了。Sorry, my bad...  just learning in hard way!
