### ISSUE TITLE
Problem about ignorePassed in searchCourse

### ISSUE THREAD

**Issue by 172698691** [NewbieOrange/SUSTech-SQL-Project2-Public#133]
1.
Should ignorePassed consider semester? For example, if semester 1 is before semester 3 and the student has passes a course in semester 3, whether this course considered as passed when searchCourse in semester 1.

2.
What's more, if the student has passes a course in semester 1,  whether this course considered as passed when searchCourse in semester 1?

**Comment by NewbieOrange** [comment]
> Should ignorePassed consider semester? For example, if semester 1 is before semester 3 and the student has passes a course in semester 3, whether this course considered as passed when searchCourse in semester 1.

Pass in any semester is considered pass.

> What's more, if the student has passes a course in semester 1, whether this course considered as passed when searchCourse in semester 1?

Same as above, yes.

**Comment by 172698691** [comment]
got it
