### ISSUE TITLE
关于searchInstructor

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#134]
Rule: firstName + lastName begins with searchInstructor
* or firstName + ' ' + lastName begins with searchInstructor
* or firstName begins with searchInstructor
* or lastName begins with searchInstructor
想问一下这个到底是什么意思

**Comment by NewbieOrange** [comment]
就是字面意思啊，满足以下任一条件则匹配：
1. firstName + lastName 由 searchInstructor 开始
2. firstName + ' ' + lastName 由 searchInstructor 开始
3. firstName 由 searchInstructor 开始
4. firstName 由 searchInstructor 开始

**Comment by 1371131436** [comment]
> 就是字面意思啊，满足以下任一条件则匹配：
> 
> 1. firstName + lastName 由 searchInstructor 开始
> 2. firstName + ' ' + lastName 由 searchInstructor 开始
> 3. firstName 由 searchInstructor 开始
> 4. firstName 由 searchInstructor 开始

由……开始到底是指什么意思啊，是指给的String以"searchInstructor"开头吗，然后我们要做的事就是提取之后的字符串，看它是不是这四种之一？

**Comment by NewbieOrange** [comment]
a 由 b 开始 = a.startsWith(b)，这样能理解吗？
