### ISSUE TITLE
关于searchCourseType和专业必修选修课

### ISSUE THREAD

**Issue by Leosang-lx** [NewbieOrange/SUSTech-SQL-Project2-Public#136]
在searchCourse方法里面的searCourseType里的几个类型在筛选的时候该如何区分呢
all，专业必修选修和跨专业都可以明白，就是用学生的专业来区分。
如何区分public呢？如何在通过课程信息区分public类型？

**Comment by NewbieOrange** [comment]
请看CourseType文档描述。
