### ISSUE TITLE
学期的第几周是咋计算的

### ISSUE THREAD

**Issue by windsliver** [NewbieOrange/SUSTech-SQL-Project2-Public#138]
如图，假如学期在6月10日开始，请问第几周是怎样算的

![image](https://user-images.githubusercontent.com/77012000/121528197-d6bd4780-ca2d-11eb-9827-b557f93fc22d.png)
请问是上面这种情况↑

还是下面这种情况↓
![image](https://user-images.githubusercontent.com/77012000/121528637-3fa4bf80-ca2e-11eb-8879-f61c7786154b.png)

**Comment by NewbieOrange** [comment]
我们保证学期第一天是周一。
