### ISSUE TITLE
about enrollCourse() in StudentService

### ISSUE THREAD

**Issue by ObsisMc** [NewbieOrange/SUSTech-SQL-Project2-Public#139]
文档里说course conflict是不能选同一个course的多个sections， 那要是选了某个course的section，然后挂了，之后再选该course的section，那么也有conflict吗？这里的 不能选多个sections 是指同一个学期不能选多个section吗？

**Comment by NewbieOrange** [comment]
是的，是指同一个学期内。

**Comment by LinkaiPeng-SUSTech** [comment]
如果数据库中A学期的B课程有了成绩，这时候在A学期中选B课程返回结果应该是什么
