### ISSUE TITLE
Begin date of semester（2）

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#14]
This is really a serious problem. I strongly recommend you to pay attention to it and give more explanation.

For these reasons:

(1)  In reality, all semesters begin on Monday in Sustech.

(2) If a semester doesn't begin on Monday, there will be tons of problems to deal with the data, which need more explanation.
      For example, If a semester doesn't begin on Monday, the first week will not have Monday. If a course on Monday with `weeklist` `[1,2,3,4,5,6......]`, the first class in the first week will be ambiguous. And the week order will be disorder as well.

All in all, If a semester begins not on Monday, should I give an error? If not, how should I order the week index? What is the range of the first week?

**Comment by JohnWestonNull** [comment]
We ensure the test semesters begin with Monday.
