### ISSUE TITLE
关于连接超时

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#140]
![image](https://user-images.githubusercontent.com/58131846/121540458-13db0700-ca39-11eb-866b-571df77264c1.png)
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30012ms.
想问一下这个Bug是什么情况，怎么解决啊

**Comment by NewbieOrange** [comment]
sql查询速度过慢，请优化你的sql
