### ISSUE TITLE
关于enrollCourse中COURSE_CONFLICT_FOUND的疑问

### ISSUE THREAD

**Issue by Antoniano1963** [NewbieOrange/SUSTech-SQL-Project2-Public#144]
我在测试enrollcourse的时候发现自己有一个样例过不去，报错信息为Enroll result error: EnrollResult.COURSE_CONFLICT_FOUND, expected: EnrollResult.SUCCESS

在我进行具体查看的时候发现11713333这位同学先选了一个学期的CS205这门课，又尝试选另外一个学期的CS205，在这种情况下不是应该按照文档里所说的：
/**
         * The student's enrolled courses has time conflicts with the section,
         * or has course conflicts (same course) with the section.
         */
        COURSE_CONFLICT_FOUND,

的第二种情况报错吗，但是答案确实SUCCESS
使用的是python

**Comment by NewbieOrange** [comment]
两个学期怎么会产生时间冲突

**Comment by Antoniano1963** [comment]
对呀，不是按照or has course conflicts (same course) with the section. 来进行处理吗，他们不是所有same course 所以报错吗

**Comment by YG-yyds** [comment]
> 对呀，不是按照or has course conflicts (same course) with the section. 来进行处理吗，他们不是所有same course 所以报错吗

那个是section吧

**Comment by Antoniano1963** [comment]
请问不是说多门课属于同一个课程就叫做course conflict吗，那个难道不是这个意思吗
这个情况里不是两节课虽然没有时间冲突，但是都属于同一门CS205这门课吗，难道一个学生还能同时选两门CS205上吗，而且都是在没给分的状态？

**Comment by NewbieOrange** [comment]
可以，course / time conflict 仅限同学期。

**Comment by Antoniano1963** [comment]
好的，麻烦学长了

**Comment by Antoniano1963** [comment]
请问一下 searchcourse里的course conflict也是仅限同学期对吧

**Comment by NewbieOrange** [comment]
是的。
