### ISSUE TITLE
searchCourse中searchInstructor参数的含义

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#145]
测试用例[11716490, 3, null, null, 沈昀, null, null, null, ALL, true, true, true, true, 10, 0]中，标准答案是

[CourseSearchEntry{course=Course{id='BIO104', name='普通生物学实验', credit=2, classHour=64, grading=HUNDRED_MARK_SCORE}, section=CourseSection{id=25, name='中英双语1班（实验课每次都计入期末成绩，且没有补课）', totalCapacity=20, leftCapacity=20}, sectionClasses=[CourseSectionClass{id=286, instructor=Instructor{id=30000188, fullName='唐博'}, dayOfWeek=WEDNESDAY, weekList=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], classBegin=5, classEnd=6, location='荔园1栋102'}, CourseSectionClass{id=287, instructor=Instructor{id=30000187, fullName='沈昀'}, dayOfWeek=WEDNESDAY, weekList=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], classBegin=9, classEnd=10, location='荔园6栋406机房'}], conflictCourseNames=[]}]

可以请问一下这里为什么可以出现不是“沈昀” 的instructor “唐博” 呢

**Comment by NewbieOrange** [comment]
文档里说了，只要有一个class完全匹配给的搜索条件，那个section就算匹配。
