### ISSUE TITLE
提交的sql文件需要有建数据库的语句吗如 create database “xxx” with encoding='xxx'

### ISSUE THREAD

**Issue by deepoceansame** [NewbieOrange/SUSTech-SQL-Project2-Public#147]
**Please make sure the testing code and data are at the latest commit**
还有config.properties是不是只要指出seviceFactory，jdbcUrl username password不做要求
**Describe the question**

**Comment by NewbieOrange** [comment]
是的，不用建库语句，我们会帮你建好正确的库
