### ISSUE TITLE
关于searchCourse测试用例的问题

### ISSUE THREAD

**Issue by Yitong806** [NewbieOrange/SUSTech-SQL-Project2-Public#151]
**Please make sure the testing code and data are at the latest commit**

**Describe the question**
请问这一条searchCourse中的测试用例中，在数据库查询语句已经发现该同学通过了该课程。请问当对这一条课程做search的时候（该条课程已经会在search的结果集中），返回的结果当中的conflictCourseName需要包含该课程吗，会不会自己和自己冲突？（假定ignore参数类型是full-true，conflict-false，passed-false，preMissing-false）
![image](https://user-images.githubusercontent.com/64548919/121670986-9d91df80-cae0-11eb-8286-9f802db9d537.png)

**Comment by NewbieOrange** [comment]
是否冲突与分数无关，对同学期的已选课，conflictCourseName会与自己冲突。

**Comment by Yitong806** [comment]
那么请问这一条测试数据里面，为什么expected里没有把本身放入测试的conflict结果中？
![image](https://user-images.githubusercontent.com/64548919/121693023-4ea57380-cafb-11eb-961c-765d7807dfa5.png)

![image](https://user-images.githubusercontent.com/64548919/121693089-5fee8000-cafb-11eb-812e-d1576a09f524.png)

**Comment by NewbieOrange** [comment]
你这个发的我也看不出来是哪一条，你把课程本身去掉能过所有测试吗？
