### ISSUE TITLE
关于searchcourse里搜索searchname的问题

### ISSUE THREAD

**Issue by TANSixu** [NewbieOrange/SUSTech-SQL-Project2-Public#152]
在代码文档里有如下对searchname的说明：
*@param searchName                 search course name. Rule: searchName in "course.name[section.name]*
1. 可是数据里并不都满足这个规则。比如
*[11718016,3,null,"光伏光热技术导论["*
在此数据中，只有半个括号。
请问此时应该抛出异常还是只搜索coursename而不管sectionname？

2. 更进一步的问题，对于这个输入*course.name[section.name]*，我的做法应该是
. 把它拆解成coursename和sectionname分别匹配
还是
. 在数据库中先创建出这样的pattern， eg. 先把数据库中的数据(coursename=金融数据分析，sectionname=英文版)join出类似*金融数据分析与数据挖掘[英文班]*， 然后再与输入的*course.name[section.name]*进行模糊匹配

**Comment by NewbieOrange** [comment]
1. in 的意思是 在..中，而不是说name是这个格式的。所以按照要求正常搜索即可。
2. 与完整名字进行模糊匹配。
