### ISSUE TITLE
关于dropCourse抛异常

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#153]
![0(E_@B (TXXI)FN9`5}K`6K](https://user-images.githubusercontent.com/58131846/121700010-0e95bf00-cb02-11eb-971e-8cfa4007a91b.png)
对于dropCourse这个方法，按照这个方法的要求，找不到成绩的时候抛异常（我们在datagrip select过了确实没有成绩），我们测到这个方法时这个输出是合理的还是不合理的？

**Comment by NewbieOrange** [comment]
学生反馈已解决。
