### ISSUE TITLE
关于错误的数据

### ISSUE THREAD

**Issue by TANSixu** [NewbieOrange/SUSTech-SQL-Project2-Public#155]
在debug时发现了很多result里的错误答案。
例如，在searchcourse中，有给定的如下param：
*[11717372, 3, null, null, null, null, 9, null, ALL, false, false, false, true, 10, 0]*
可以看到，这里的*searchClassTime* 为9
我们的程序给出了正确的对应classtime的答案：
*CourseSearchEntry{course=Course{id='RD472', name='计算机程序设计基础', credit=2, classHour=32, grading=HUNDRED_MARK_SCORE}, section=CourseSection{id=1406, name='中文班', totalCapacity=66, leftCapacity=66}, sectionClasses=[CourseSectionClass{id=2195, instructor=User{id=30000136, fullName='郑锋'}, dayOfWeek=THURSDAY, weekList=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], classBegin=9, classEnd=10, location='荔园6栋402机房'}], conflictCourseNames=[]}*

可是result给出了如下显然不满足classtime限制的答案：
*CourseSearchEntry{course=Course{id='RD472', name='计算机程序设计基础', credit=2, classHour=32, grading=HUNDRED_MARK_SCORE}, section=CourseSection{id=1406, name='中文班', totalCapacity=66, leftCapacity=66}, sectionClasses=[CourseSectionClass{id=2211, instructor=User{id=30000136, fullName='郑锋'}, dayOfWeek=THURSDAY, weekList=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], classBegin=5, classEnd=6, location='荔园1栋101'}, CourseSectionClass{id=2195, instructor=User{id=30000136, fullName='郑锋'}, dayOfWeek=THURSDAY, weekList=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], classBegin=9, classEnd=10, location='荔园6栋402机房'}], conflictCourseNames=[]}*

可见，result给出的答案包含一个5-6的class，显然错误。
这样的错误在数据中并不少，请问应该如何处理？

**Comment by Zhou-Yicheng** [comment]
我也遇到过这个问题，假如你搜`刘德华`，理论课和实验课都应该返回，而不是只返回理论课。

**Comment by NewbieOrange** [comment]
是的，这是搜索选课，你不可能只选实验课，应当返回所有时间段

**Comment by TANSixu** [comment]
> 是的，这是搜索选课，你不可能只选实验课，应当返回所有时间段

您好，麻烦问下该issue中的通过限制选课中result的错误数据应该怎么处理呢 ？ 详见issue描述

**Comment by NewbieOrange** [comment]
> > 是的，这是搜索选课，你不可能只选实验课，应当返回所有时间段
> 
> 您好，麻烦问下该issue中的通过限制选课中result的错误数据应该怎么处理呢 ？ 详见issue描述

不是数据错了，你看我上面的回复，预期结果是你要返回那个section的全部class。

**Comment by TANSixu** [comment]
> > > 是的，这是搜索选课，你不可能只选实验课，应当返回所有时间段
> > 
> > 
> > 您好，麻烦问下该issue中的通过限制选课中result的错误数据应该怎么处理呢 ？ 详见issue描述
> 
> 不是数据错了，你看我上面的回复，预期结果是你要返回那个section的全部class。

那请问这样的话那些对class的搜索选项有什么用呢？

**Comment by NewbieOrange** [comment]
> 那请问这样的话那些对class的搜索选项有什么用呢？

请看文档，说明是对section中**任一**class进行筛选。

**Comment by baiyanlali** [comment]
> > > 是的，这是搜索选课，你不可能只选实验课，应当返回所有时间段
> > 
> > 
> > 您好，麻烦问下该issue中的通过限制选课中result的错误数据应该怎么处理呢 ？ 详见issue描述
> 
> 不是数据错了，你看我上面的回复，预期结果是你要返回那个section的全部class。


> > 那请问这样的话那些对class的搜索选项有什么用呢？
> 
> 请看文档，说明是对section中**任一**class进行筛选。

请问是说只要某一个class满足条件，整个section内的所有class都返回吗？

**Comment by NewbieOrange** [comment]
是的，某一个class同时满足所有条件。
