### ISSUE TITLE
TypeError: unhashable type: 'Course'

### ISSUE THREAD

**Issue by zion302** [NewbieOrange/SUSTech-SQL-Project2-Public#156]
dto.py 里面 class Course 没有 定义 __hash__，在 Mapping[Course, Grade] 就会出这个错误，也是就Course object不能作为key.
加上hash定义后，就可以了。 但这个dto.py学生not supposed to modify! 还是说有其他不用 hashable key的mapping方法？
![image](https://user-images.githubusercontent.com/25132775/121761180-e4271e80-cb60-11eb-8f80-90f873c1ed7d.png)

**Comment by NewbieOrange** [comment]
最终评测dto会加上hash
