### ISSUE TITLE
jar包里只包含依赖的class文件不包含自身编译class文件, 这正常吗

### ISSUE THREAD

**Issue by Camsyn** [NewbieOrange/SUSTech-SQL-Project2-Public#158]
**Please make sure the testing code and data are at the latest commit**

**Describe the question**

**Comment by NewbieOrange** [comment]
请再运行maven-package，并提交两个（无with-dependencies与有的）jar文件。

不必过于担心，只要提交了完整project代码，我们在无法运行jar时会重新编译你们的代码。

**Comment by Camsyn** [comment]
请问 我打jar包的时候把你们给的框架也打进去了, 这可以可以吗

**Comment by NewbieOrange** [comment]
可以
