### ISSUE TITLE
Some questions about exceptions

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#17]
When should I throw an EntityNotFoundException?During remove and query or just in query?
When adding an element, if I failed, what should I return?

**Comment by NewbieOrange** [comment]
> When adding an element, if I failed, what should I return?

Nothing. Throw an exception instead.

**Comment by dengsh12** [comment]
> > When adding an element, if I failed, what should I return?
> 
> Nothing. Throw an exception instead.

But what type of exception should I throw?

**Comment by JohnWestonNull** [comment]
It depends why the adding failed.

**Comment by dengsh12** [comment]
> It depends why the adding failed.

emmmmm,for example, in DepartmentService, if adding a new department which has the same name with an existing department,  they are reapeated and the adding failed, but what exception should I throw?

**Comment by ziqin** [comment]
> emmmmm,for example, in DepartmentService, if adding a new department which has the same name with an existing department, they are reapeated and the adding failed, but what exception should I throw?

It would be fine to throw an `IntegrityViolationException`.
