### ISSUE TITLE
Data type wrong

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#2]
The credit of course is int.

![image](https://user-images.githubusercontent.com/56679342/116804446-7810ce00-ab51-11eb-9a94-589ed4f1b322.png)

![image](https://user-images.githubusercontent.com/56679342/116804459-8f4fbb80-ab51-11eb-94e9-3c56cf0fc3c0.png)

But actually, some course has 0.5 credit.

**Comment by NewbieOrange** [comment]
We guarantee all course credit values will be integer.
