### ISSUE TITLE
还有一个关于参数意义的问题

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#21]
```java
@Override
    public int addCourseSection(String courseId, int semesterId, String sectionName, int totalCapacity)
```
请问这个方法当中并没有指定CourseSection当中的id，那么应该怎么知道是哪一个对应的CourseSection呢？注释中提到：For example it can represent the id of section "No.1 Chinese class of database principle"，那么这个id是自增的吗？还是有什么方法可以指定？

**Comment by NewbieOrange** [comment]
这个是add，你需要添加一个新的CourseSection，那么肯定没有你说的“对应”关系，README中已说明请使用自增id。
