### ISSUE TITLE
Some another questions about exceptions

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#22]
I am confused about the IntegrityViolationException, in removeCourseSection method, if there are some removeCourseSectionClass is under the removeCourseSection the method want to remove, should I remove the relative CourseSectionClass or just throw an IntegrityViolationException?

**Comment by JohnWestonNull** [comment]
We're looking into this matter, please stay tuned.
If you have any suggestion about this issue, feel free to mention in the issue.

**Comment by dengsh12** [comment]
> We're looking into this matter, please stay tuned.
> If you have any suggestion about this issue, feel free to mention in the issue.

I think...maybe to throw an IntegrityViolationException is an easy way

**Comment by JohnWestonNull** [comment]
It's an approach, but it may be inconvenient to use.
We're consider adding a cascade parameter into all "remove" interfaces to resolve this matter.
