### ISSUE TITLE
Some more questions about return value

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#23]
In many methods, such as getUser(), if when I am doing a query or insert, there maybe an SQLException happen, when SQLException happen during my method(such as getUser()), what should I return?Should I throw an SQLException as well or repeat the process until success?

**Comment by ziqin** [comment]
For `SQLException` caused by reasons like broken network instead of constraint violation, you can throw a `RuntimeException` wrapping it.
