### ISSUE TITLE
What functions need to be implemented

### ISSUE THREAD

**Issue by pzyxhkx** [NewbieOrange/SUSTech-SQL-Project2-Public#24]
Like login, student information management, course information management, course selection, view course selection information, and what else needed ?

**Comment by ziqin** [comment]
You need to implement all the interfaces provided in the `cn.edu.sustech.cs307.service` package.

**Comment by ziqin** [comment]
You also need to implement `cn.edu.sustech.cs307.factory.ServiceFactory`.
