### ISSUE TITLE
确认一下prerequisite（下称pre）的规则

### ISSUE THREAD

**Issue by deepoceansame** [NewbieOrange/SUSTech-SQL-Project2-Public#3]
root pre: an  'andpre' named A. Its terms: [andpre B, orpre C, coursepre D]
B's terms: [orpre E, coursepre F]
C's terms:[andpre G, coursepre H]
E's terms:[coursepre I, coursepre J]
G's terms:[coursepre K, coursepre L]
表示的pre就是
 'B' and 'C' and D = 
('E' and F) and ('G' or H) and D = 
( (I or J)  and  F ) and ( (K and L) or H) and D

**Comment by deepoceansame** [comment]
是不是那个addCourse的 @Nullable Prerequisite coursePrerequisite很容易误解

**Comment by ziqin** [comment]
> root pre: an 'andpre' named A. Its terms: [andpre B, orpre C, coursepre D]
> B's terms: [orpre E, coursepre F]
> C's terms:[andpre G, coursepre H]
> E's terms:[coursepre I, coursepre J]
> G's terms:[coursepre K, coursepre L]
> 表示的pre就是
> 'B' and 'C' and D =
> ('E' and F) and ('G' or H) and D =
> ( (I or J) and F ) and ( (K and L) or H) and D

是的。

Yes, you're right.

**Comment by ziqin** [comment]
> 是不是那个addCourse的 @nullable Prerequisite coursePrerequisite很容易误解

先修课为 `null` 则表示没有现有先修依赖。

A null prerequisite means no prerequisite.

方法参数 `coursePrerequisite` 的命名确实容易让人误解其类型。在 `addCourse()` 方法中，该参数的类型实际上可以为 `Prerequisite` 接口的三个实现类中的任意一个。理解时建议忽略这个参数名的“course”前缀。

I have to admit that the parameter name `coursePrerequisite` is confusing. In `addCourse()` method, the actual argument type can be any one of those 3 classes who implemented the `Prerequisite` interface. You're suggested to ignore the prefix “course” there.
