### ISSUE TITLE
Problem about weeklist

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#30]
Is the weekList's element already sorted or not?

**Comment by dengsh12** [comment]
another problem:are the two CourseSectionClass from the same coursesection has the same weeklist?

**Comment by NewbieOrange** [comment]
> Is the weekList's element already sorted or not?

You may assume it is sorted.

> are the two CourseSectionClass from the same coursesection has the same weeklist

It may have different weeklist.
