### ISSUE TITLE
Can I define new methods for given DTOs?

### ISSUE THREAD

**Issue by dreamking60** [NewbieOrange/SUSTech-SQL-Project2-Public#34]
If I can define some new functions in the class for some special databases? But if I define, maybe it won't execute in your test.

**Comment by ziqin** [comment]
You may mention the specific database you want to use here.

**Comment by dreamking60** [comment]
Sorry, it is not special database, it is special table.

**Comment by NewbieOrange** [comment]
No, please note that the DTOs are only for transfering data between our code and your code, as the name suggests. You may create your own classes to handle your table if needed, in which case you still need to strictly follow the given interfaces (convert your classes to/from our DTOs when needed).
