### ISSUE TITLE
Do we need primary keys and foreign keys?

### ISSUE THREAD

**Issue by dreamking60** [NewbieOrange/SUSTech-SQL-Project2-Public#35]
We don't see any data, which means that it is hard for us to choose the private key, I wonder if it need for us to build private key? And for foreign key, we do not know the code insert order, so it is means that we don't need to design foreign key?

**Comment by dreamking60** [comment]
If this means that all the table we should have a id make by ourselves and anytime we insert only need to check the only id?

**Comment by ziqin** [comment]
By “private key”, do you mean “primary key”?

Note that “private key” is a term in cryptography.

**Comment by dreamking60** [comment]
> By “private key”, do you mean “primary key”?
> 
> Note that “private key” is a term in cryptography.

oh sorry, it is primary key.

**Comment by ziqin** [comment]
You are supposed to define both primary keys and foreign keys.
