### ISSUE TITLE
What kinds of courseId are valid?

### ISSUE THREAD

**Issue by dreamking60** [NewbieOrange/SUSTech-SQL-Project2-Public#36]
What the principle of the invalid, it seems not clearly, if I have a courseid = 'CS307', we know this is valid, But if it is courseid = '307CS', maybe it is invalid? Other value are the same, it seems no simple to judge valid and throw out some parameter.

**Comment by ziqin** [comment]
A `courseId` is valid if it has been added to the system with `CourseService#addCourse()`.
