### ISSUE TITLE
The meaning of course section and class

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#37]
see function `public EnrollResult enrollCourse(int studentId, int sectionId)`

this function joins a student and a section. But from a section, we can't know the time, location, instructors, so we can't know what class a student selects.

So we can't give the correct message when a student enrollCourse. Because **the whole project** not let a student choose a class. So we can never get when a student has a class.

In reality, we choose a class not a section to enroll in a course.

**Comment by xbdeng** [comment]
我用中文描述一下可能更清楚......

整个project选课只选择了section（比如理论课中文1班），没有任何地方选择一个class（lab班）

课程的时间地点信息是存在class里的（这个是接口给出的），而学生通过`public EnrollResult enrollCourse(int studentId, int sectionId)`选完课永远不知道自己的上课时间地点老师是啥，因为整个框架没有给section添加时间地点，只是给section添加了class，但section和class不是一一对应的。

这样就没办法判断学生选课是否会有时间冲突，因为学生选的课没有时间信息。

**Comment by ziqin** [comment]
This is actually a wording problem. I have to admit “class” is not a good term to represent what we really mean.

Whenever a student is enrolled in a course section, he is enrolled in all “classes” (usually both the class for the lecture and the class for the lab) of that course section.

In the context of this project, a “course section class” is usually tied to a classroom. In many cases, you may treat a “course section” as a pair of “course section class” (i.e. the lecture and the lab).

**Comment by xbdeng** [comment]
会不会出现有的section没有添加class的情况。

**Comment by ziqin** [comment]
> 会不会出现有的section没有添加class的情况。

在现实中确实会有这样的例子。例如，一些自主实践类/外校交流学分转换的课程没有专门的老师和教室，但需要将成绩录入系统。在这种情况下，学生课表上不会出现相应的上课安排，但依然可以为他计算成绩。
