### ISSUE TITLE
User's full name 

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#4]
The student and instructor are given a first name and last name.

But we need to return a full name.

What is the full name?

**Comment by NewbieOrange** [comment]
A user's full name is: first_name || ' ' || last_name, if both first name and last name is alphabetical, otherwise first_name || last_name.

For example, if a user has first name `David` and last name `Lee` then the full name is `David Lee`; if another user has first name `张` and last name `三`, the full name is `张三`.

**Comment by 172698691** [comment]
> A user's full name is: first_name || ' ' || last_name, if both first name and last name are alphabetical, otherwise first_name || last_name.
> 
> For example, if a user has first name `David` and last name `Lee` then the full name is `David Lee`; if another user has first name `张` and last name `三`, the full name is `张三`.

But for Chinese names, shouldn't the last_name come before the first_name?(like last_name || first_name)
For example, if the full name is '张三‘, then the first_name is '三’ and the last_name is '张'.

**Comment by NewbieOrange** [comment]
> But for Chinese names, shouldn't the last_name come before the first_name?(like last_name || first_name)

No, please follow the documentation strictly.

**Comment by LinkaiPeng-SUSTech** [comment]
Is there any possibility that both alphabetical and non-alphabetical characters appear in a user's name such as 张David

**Comment by NewbieOrange** [comment]
> Is there any possibility that both alphabetical and non-alphabetical characters appear in a user's name such as 张David

Please refer to the documentation.
