### ISSUE TITLE
passedPrerequisitesForCourse 

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#40]
This function will check whether a student can choose a course.

But the passed course must pass before this semester.

This function doesn't know what semester is now. How could I check the `passedPrerequisitesForCourse` 

Just ignore the time and check the score of the student directly?

**Comment by NewbieOrange** [comment]
If the student has any course score record that is passed (>=60 or `PASS`), then he has passed the course.

**Comment by ziqin** [comment]
Duplicate with https://github.com/NewbieOrange/SUSTech-SQL-Project2-Public/issues/39.
