### ISSUE TITLE
List<CourseSearchEntry> searchCourse

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#41]
There are some problems with this function.

1. What is the `searchName`, should I use a Fuzzy query?

2. `searchCourseType` If a student doesn't have a major, what is the searchCourseType.

**Comment by JohnWestonNull** [comment]
1. Please read the document.
`* @param searchName                 search course name. Rule: searchName in "course.name[section.name]"`
2. Major is a must, also read the document.

**Comment by xbdeng** [comment]
Sorry, the document is not clear enough.

Should I use a Fuzzy query to search the `searchName`

I can't understand the `search course name. Rule: searchName in "course.name[section.name]"`  what is "in" ?

**Comment by NewbieOrange** [comment]
> what is "in" ?

a in b = b.contains(a)

**Comment by xbdeng** [comment]
如果学生必须有专业，那么当调用 `void removeMajor(int majorId);` 时，这个专业的所有学生都会被一起删除吗？这不符合常理。

**Comment by NewbieOrange** [comment]
> 如果学生必须有专业，那么当调用 void removeMajor(int majorId); 时，这个专业的所有学生都会被一起删除吗？

Yes.

> 这不符合常理。

For simplicity's sake, we make all remove methods cascading delete.
