### ISSUE TITLE
Remove  Exception

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#42]
If remove a not exist message(the id does not exist), what type of exception should I through?

**Comment by ziqin** [comment]
You can throw an `EntityNotFoundException`.

**Comment by HouraisanMokou** [comment]
I am little confused about what the answer "you can throw..." means. Does it means that I can choose whether throwing such exception or not, or it means that such exception is asked to be thrown?-
