### ISSUE TITLE
page index of searchCourse

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#43]
If the page index is so large that there is no message, should I through an exception or return a null list?

**Comment by ziqin** [comment]
Return an empty list.

**Comment by LinkaiPeng-SUSTech** [comment]
what is the start value of page index, starting from 0 or 1

**Comment by ziqin** [comment]
> what is the start value of page index, starting from 0 or 1

0
