### ISSUE TITLE
searchCourse in student service

### ISSUE THREAD

**Issue by saynaaskh** [NewbieOrange/SUSTech-SQL-Project2-Public#44]
I have some question about the parameter "searchClassTime" and the return type CourseSearchEntry:
1. this means I should get the classes whose interval (from begin time to end time) cover the given search time?
2. what is the meaning of time conflicting courses in CourseSearchEntry? conflict with the time of classes that the student has enrolled?

**Comment by NewbieOrange** [comment]
> this means I should get the classes whose interval (from begin time to end time) cover the given search time?

If a course section has **any** class which [begin, end] contains the search time, then the section satisfy the condition.

> what is the meaning of time conflicting courses in CourseSearchEntry? conflict with the time of classes that the student has enrolled?

Please pull the latest commit and check the document.


```java
 /*
     * Course conflict is when multiple sections belong to the same course.
     * Time conflict is when multiple sections have time-overlapping classes.
     * Note that a section is both course and time conflicting with itself!
* /
```
