### ISSUE TITLE
Questions about ignoreConflict in StudentService

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#48]
Can you explain what to do when ignoreConflict is true and there is a time or course conflict? 
More specifically, if ignoreConflict is true, the returned list of CourseSearchEntry should contain no conflicting sections or conflictCourseNames in CourseSearchEntry of each section contains nothing.

**Comment by NewbieOrange** [comment]
> If ignoreConflict is true, the returned list of CourseSearchEntry should contain no conflicting sections.

**Comment by Ddduanxt** [comment]
Then if two sections conflict with each other, which one should I keep? Or should I remove both?

**Comment by NewbieOrange** [comment]
> Then if two sections conflict with each other, which one should I keep? Or should I remove both?

Remove the ones conflict with **sections the student has selected**.

**Comment by Ddduanxt** [comment]
If the start time of a class is the same with the end time of another class, will these two classes be called conflict? That is to say the judgement should be start_time>end_time or start_time>=end_time if 2 classes do not conflict with each other?

**Comment by Ddduanxt** [comment]
Also, should we include the section itself in the list of conflicting courses?

**Comment by NewbieOrange** [comment]
> If the start time of a class is the same with the end time of another class, will these two classes be called conflict?

Yes, the class time represents a closed interval.

> Also, should we include the section itself in the list of conflicting courses?

Yes, note that the conflicting courses are from the student's enrolled courses.

**Comment by NewbieOrange** [comment]
> 应该ignoreConflict is false的时候，返回的list才不应该有conflicting sections吧？

When ignoreConflict is true, it means you should **ignore** conflicting sections, thus there is no conflicting section in the returning list.

> 如果学生没有选过任何课，现在course A有两个section（彼此为course conflict），但又不与学生选过的课冲突（不符合remove条件），返回的结果中应该保留什么

Then keep both sections, as the document did not say to remove them.

**Comment by LinkaiPeng-SUSTech** [comment]
1.searchCourse方法中的ignoreconflict是在返回的list中删除和已选课程冲突的？
2.searchCourse返回的list中每一个CourseSearchEntry对象中的conflictCourseNames list中存储的是当前这个section和searchCourse返回的list中有conflict的课程？与学生是否选过该门课程没有关系？

**Comment by LinkaiPeng-SUSTech** [comment]
1.conflictCourseNames存的是该学生已选的课程中和当前这门课冲突的所有课程名字？
2.如果1是对的，在ignoreconflict is true的情况下，返回的所有coursesearchentry的conflictCourseNames都应该为null？

**Comment by NewbieOrange** [comment]
> conflictCourseNames存的是该学生已选的课程中和当前这门课冲突的所有课程名字？

Yes.

> 在ignoreconflict is true的情况下，返回的所有coursesearchentry的conflictCourseNames都应该为null？

Yes.

**Comment by Antoniano1963** [comment]
1 请问ignoreconflict是 flase的时候 我searchCourse方法返回的List<CourseSearchEntry>里的课程是只能是不与学生以选课程冲突的课程吗？
2 请问在1成立的情况下，既然list里的课程不与学生已选课程冲突，那么每个CourseSearchEntry对象中的conflictCourseNames是不是为空
3请问在2成立的情况下，ignoreconflict为flase的时候List里的conflictCourseNames都是空的，然后ignoreconflict为True的时候，List里的conflictCourseNames（您之前说的）那这个变量还有什么用
4 还是说1 不成立 ignoreconflict是 flase 的时候，List<CourseSearchEntry>里的课程包含了与学生已选课程冲突的课程，这样每个CourseSearchEntry对象中的conflictCourseNames记录的就是这些冲突课程具体和学生哪些以选课程冲突了？
请问4理解的是对的吗

**Comment by NewbieOrange** [comment]
> 还是说1 不成立 ignoreconflict是 flase 的时候，List里的课程包含了与学生已选课程冲突的课程，这样每个CourseSearchEntry对象中的conflictCourseNames记录的就是这些冲突课程具体和学生哪些以选课程冲突了？

Yes.

**Comment by Ddduanxt** [comment]
> 在ignoreconflict is true的情况下，返回的所有coursesearchentry的conflictCourseNames都应该为null？

> Yes.
这里是应该返回空的List还是null呢？

**Comment by NewbieOrange** [comment]
You should return empty list in this case.
