### ISSUE TITLE
Questions about exception

### ISSUE THREAD

**Issue by Leo0506** [NewbieOrange/SUSTech-SQL-Project2-Public#49]
If I want to get/delete a user whose id is 1 but it doesn't exist in the user table, I run this SQL statement and I will not get an error. But should I throw an EntityNotFoundException in this case? If not, when should I throw this kind of exception?

**Comment by Zhou-Yicheng** [comment]
![image](https://user-images.githubusercontent.com/52224018/119629787-ec811900-be40-11eb-9ca6-4c908b583258.png)

**Comment by Leo0506** [comment]
thx
