### ISSUE TITLE
What should addDepartment() return? 

### ISSUE THREAD

**Issue by HouraisanMokou** [NewbieOrange/SUSTech-SQL-Project2-Public#50]
some method using to adding something like addDepartment() need to return a int value, i am confused that whether the int value is the attribute of id
一些加入放方法比如说addDepartment() 要返回一个 int值，我想知道这个int值是不是就是可以任意取的不重复的id

**Comment by Zhou-Yicheng** [comment]
要返回你数据库里存的那个ID（可能是自增的）

**Comment by NewbieOrange** [comment]
> 我想知道这个int值是不是就是可以任意取的不重复的id

Yes, please return a unique identifier (for the same class of entity).
