### ISSUE TITLE
What if single CourseSectionClass has multiple instructors?

### ISSUE THREAD

**Issue by Camsyn** [NewbieOrange/SUSTech-SQL-Project2-Public#52]
Q1: In the method `addCourseSectionClass` , there is a just one insturctor_id, but in reality, one section class could has many teachers, How to solve this problem? 
Q2: Suppose all the parameters are valid, what if I invoke the same(or just change the instructorId) `addCourseSectionClass` twice? Should I throw an exception?

**Comment by NewbieOrange** [comment]
> Q1: In the method addCourseSectionClass , there is a just one insturctor_id, but in reality, one section class could has many teachers, How to solve this problem?

Implement the service as the document required.

> Q2: Suppose all the parameters are valid, what if I invoke the same(or just change the instructorId) addCourseSectionClass twice? Should I throw an exception?

You may either throw an exception or add without error.
