### ISSUE TITLE
关于addCourse() 的问题

### ISSUE THREAD

**Issue by NYH-Sustech** [NewbieOrange/SUSTech-SQL-Project2-Public#54]
在添加一个新的 course 时，是否需要先逐一检查新的 course 的每一个 coursePrerequisite 是否在 course 表里面已经存在？

**Comment by NewbieOrange** [comment]
> 在添加一个新的 course 时，是否需要先逐一检查新的 course 的每一个 coursePrerequisite 是否在 course 表里面已经存在？

不确定你为什么需要逐一检查，但是如果CoursePrerequisite的课程不存在自然需要抛出异常。

**Comment by NYH-Sustech** [comment]
> 不确定你为什么需要逐一检查，但是如果CoursePrerequisite的课程不存在自然需要抛出异常。

一个 course 的先修课不是有很多中组合吗，自然也包含了很多个 CoursePrerequisite 的实例吧，那意思就是我需要去检查了是吧！谢谢

**Comment by xbdeng** [comment]
> 但是如果CoursePrerequisite的课程不存在自然需要抛出异常

所以当删除一个课程时，这个课程的后续课程也会被全部连带一起删除吗？
