### ISSUE TITLE
关于 addSemester() 的问题

### ISSUE THREAD

**Issue by NYH-Sustech** [NewbieOrange/SUSTech-SQL-Project2-Public#55]
在 addSemester() 中，传入的参数 Date begin, Date end 为 **java.sql.Date** 类型，如果我的测试样例为
**addSemester("2020春季", new Date(2020, 2, 24), new Date(2020, 6, 22));**
那么在 java 存入数据库时会把该日期转化为 **3920-03-24** 和 **3920-07-22**
请问在基准测试中，你们传入的 Date 的情况是什么样子的，需要我们自己减去 1900 吗？

**Comment by NewbieOrange** [comment]
请查看`java.sql.Date`的文档，构造器的第一个参数并不是公元年份。

**Comment by NYH-Sustech** [comment]
是的，我想知道的是你们在测试时传入的 Date 类型的参数是否是 addSemester("2020春季", new Date(2020 - 1900, 2, 24), new Date(2020 - 1900, 6, 22)); 以保证在我们数据库中是公元纪年 2020-02-24

**Comment by NewbieOrange** [comment]
> 是的，我想知道的是你们在测试时传入的 Date 类型的参数是否是 addSemester("2020春季", new Date(2020 - 1900, 2, 24), new Date(2020 - 1900, 6, 22)); 以保证在我们数据库中是公元纪年 2020-02-24

那肯定。
