### ISSUE TITLE
void removeCourse(String courseId)的问题

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#56]
当删除的一个课程是后续课程的先修课的，后面的课程是否一起被删除

**Comment by NewbieOrange** [comment]
No, just delete the prerequisite entry.

**Comment by xbdeng** [comment]
插入先修课时，你们保证了先修课的叶子节点是课程不是and或者or

![image](https://user-images.githubusercontent.com/56679342/120091629-8695d980-c13f-11eb-91ec-048ae2caae1c.png)

删除这个课程，可能造成后续课程先修课里的叶子节点出现异常

这里能给出更加具体的规定吗，是不需要修这门被删的课了还是？
