### ISSUE TITLE
Question about enum CourseType

### ISSUE THREAD

**Issue by SpaceIshtar** [NewbieOrange/SUSTech-SQL-Project2-Public#58]
I'm wondering what is the difference between ALL and PUBLIC type in CourseType. How can I distinguish them? Could you please give me an example?

**Comment by NewbieOrange** [comment]
`ALL` means literally all courses.

`PUBLIC` means all courses **except** those from any major's compulsory or elective courses.

**Comment by Zhou-Yicheng** [comment]
![image](https://user-images.githubusercontent.com/52224018/121035230-4211da00-c7e0-11eb-9456-d19f5c4624b8.png)
