### ISSUE TITLE
关于getCourseTable里date参数使用

### ISSUE THREAD

**Issue by xuzhi2021** [NewbieOrange/SUSTech-SQL-Project2-Public#59]
请问在courseService里的getCourseTable方法，我们需要根据传入参数date（年月日）来判断当前是第几教学周，然后再给出这一周这个学生的课表吗？如果是这样的话我们应该怎么判断当前是第几教学周呢？

**Comment by NewbieOrange** [comment]
通过semester里面的begin date算
