### ISSUE TITLE
关于课程剩余容量的问题

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#60]
再添加course section的时候是把left capacity设置成和total capacity一样，然后再一个学生通过enrollCourse返回SUCCESS的时候同时将这个学生选上这门课以及left capacity-1 吗。那addEnrolledCourseWithGrade方法也需要将课程容量减去新添加的人数吗，以及这个方法是否需要判断section还有没有剩余容量

**Comment by NewbieOrange** [comment]
> 再添加course section的时候是把left capacity设置成和total capacity一样，然后再一个学生通过enrollCourse返回SUCCESS的时候同时将这个学生选上这门课以及left capacity-1 

Yes.

> 那addEnrolledCourseWithGrade方法也需要将课程容量减去新添加的人数吗，以及这个方法是否需要判断section还有没有剩余容量

No, you do not need to change `leftCapacity` with `addEnrolledCourseWithGrade`. This function directly adds the enrollment without checking anything (other than the student id and course section id exists).

**Comment by Ddduanxt** [comment]
那如果grade是null就不给这个学生这门课添加成绩，效果和这学期选课一样？

**Comment by Zhou-Yicheng** [comment]
> 那如果grade是null就不给这个学生这门课添加成绩，效果和这学期选课一样？

不一样 这个方法会忽略先修课要求

**Comment by Ddduanxt** [comment]
如果一门课程是13级但是Grade里面传的是百分制，文档中的your system should not accept the other type of grade 是指就只将这个学生和课程加进去不添加成绩还是整个就不添加这一行呢

**Comment by ziqin** [comment]
> 如果一门课程是13级但是Grade里面传的是百分制，文档中的your system should not accept the other type of grade 是指就只将这个学生和课程加进去不添加成绩还是整个就不添加这一行呢

整个操作不应存在成功与失败间的中间态。

BTW, one issue for one problem. 新问题请开新 issue。
