### ISSUE TITLE
Is there cases that instructor has same user id with a student. 

### ISSUE THREAD

**Issue by HouraisanMokou** [NewbieOrange/SUSTech-SQL-Project2-Public#61]
Q1: Is there cases that instructor A has same user id with a student B (A and B is different person)?
Q2: If the answer of Q1 is no, when adding instructors, should I check that the instructor id to insert does not appear in all student id?

**Comment by NewbieOrange** [comment]
> Is there cases that instructor A has same user id with a student B (A and B is different person)?

No, this is indicated by the getUser method.

> If the answer of Q1 is no, when adding instructors, should I check that the instructor id to insert does not appear in all student id?

Yes, otherwise your getUser result will be ambiguous.
