### ISSUE TITLE
Problem about addEnrolledCourseWithGrade

### ISSUE THREAD

**Issue by LinkaiPeng-SUSTech** [NewbieOrange/SUSTech-SQL-Project2-Public#65]
Is there any possibility that the student has already passed or enrolled in the course the given sectionid corresponding to

**Comment by NewbieOrange** [comment]
In such case, please throw an `IntegrityViolationException`.

**Comment by LinkaiPeng-SUSTech** [comment]
setEnrolledCourseGrade遇到这种情况也是直接抛异常吗

**Comment by NewbieOrange** [comment]
> 
> 
> setEnrolledCourseGrade遇到这种情况也是直接抛异常吗

No, just update the grade.
