### ISSUE TITLE
关于IntegrityViolationException

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#66]
想问一下关于参数“非法”的范围，是仅指该null的没有null，还是延伸到了入参的id已存在表中、外键到的另一张表中找不到入参等这些会报SQLException的情况？由于入参导致SQLException抛出的情况在IntegrityViolationException的范围之内吗

**Comment by NewbieOrange** [comment]
> 延伸到了入参的id已存在表中、外键到的另一张表中找不到入参等这些会报SQLException的情况？

Yes.

> 由于入参导致SQLException抛出的情况在IntegrityViolationException的范围之内吗

Yes.

**Comment by 1371131436** [comment]
> > 延伸到了入参的id已存在表中、外键到的另一张表中找不到入参等这些会报SQLException的情况？
> 
> Yes.
> 
> > 由于入参导致SQLException抛出的情况在IntegrityViolationException的范围之内吗
> 
> Yes.

那会有那种没有@nullable的参量为null的数据吗（这种情况下也要抛异常？）

**Comment by NewbieOrange** [comment]
> 那会有那种没有@nullable的参量为null的数据吗

不会
