### ISSUE TITLE
关于getAllCourse方法问题

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#67]
考虑CourseService的如下方法：
```java
List<Course> getAllCourses();
```
考虑尝试先后添加CS205, CS102A, CS307三门课程，然后通过类似于select *的语句拿出所有课程。此时返回的结果顺序有可能与预先加入的顺序有所差异（诸如查询返回的结果是CS102A, CS205和CS307，而标答是CS205, CS102A, CS307），这样一来结果就会与答案因顺序不同而导致错误。请问测试时会考虑返回结果集的顺序问题吗？

**Comment by Zhou-Yicheng** [comment]
get_all_users()方法也需要按学工号顺序返回吗？

**Comment by NewbieOrange** [comment]
getAll*()方法无需考虑顺序，测试时会忽略顺序。
