### ISSUE TITLE
关于courseSection

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#68]
CourseSection类里面不包含SemesterID,但在courseService的addCourseSection有SemesterID这样的入参，那么，在不同学期的“数据库中文一班”到底可以算是同一个CourseSection还是不同的CourseSection呢（也就是共用一个pk的id还是各自一个id)?

**Comment by NewbieOrange** [comment]
> CourseSection类里面不包含SemesterID

Only when returning section, we do not require you to have semester ID. Note that when `addCourseSection` we give you the semester ID.

**Comment by 1371131436** [comment]
> > CourseSection类里面不包含SemesterID
> 
> Only when returning section, we do not require you to have semester ID. Note that when `addCourseSection` we give you the semester ID.

不太明白，我们纠结于两种设计，一种是在CourseSection表里面加入SemesterID关联Semester表，另一种是加一张新表存SectionID和SemesterID的credit表。

**Comment by NewbieOrange** [comment]
> 不太明白，我们纠结于两种设计，一种是在CourseSection表里面加入SemesterID关联Semester表，另一种是加一张新表存SectionID和SemesterID的credit表。

只要符合结果任何设计均可。
