### ISSUE TITLE
addEnrolledCourseWithGrade Grade参数与课程pf还是13级不符的问题

### ISSUE THREAD

**Issue by Ddduanxt** [NewbieOrange/SUSTech-SQL-Project2-Public#69]
请问your system should not accept the other type of grade 是指添加这个同学和section的选课信息但不接受错误的成绩还是说就直接不添加整一行

**Comment by Ddduanxt** [comment]
以及这种情况需要报错吗

**Comment by NewbieOrange** [comment]
如果与课程的给分类型不符，请抛出`IntegrityViolationException`.

**Comment by LinkaiPeng-SUSTech** [comment]
请问setEnrolledCourseGrade方法中，类型不符也是抛IntegrityViolationException吗

**Comment by NewbieOrange** [comment]
> 请问setEnrolledCourseGrade方法中，类型不符也是抛IntegrityViolationException吗

Yes.
