### ISSUE TITLE
meanings of id in CourseSectionClass and CourseSection

### ISSUE THREAD

**Issue by JMZ-kk** [NewbieOrange/SUSTech-SQL-Project2-Public#7]
What's the detailed meanings of the id in these two classes?  For example, we have five classes of course A and course B:"No.1 A class", "No.2 A class", "No.3 A class";  "No.1 B class", "No.2 B class".  What should these id be? "1 2 3 1 2" or "1 2 3 4 5"?

**Comment by NewbieOrange** [comment]
The id can be any arbitrary unique integer (like automatically generated ones).

**Comment by NewbieOrange** [comment]
> If all the CourseSection ID is totally automatically generated ones, why the "equals" method in CourseSection.java needs totalCapacity, leftCapacity and name to check whether the two objects are equivalent ?

That is how a data object works. You need to check all fields since even if they represents the same object in database (same id), they may be in different state (e.g. have different contents, etc).
