### ISSUE TITLE
关于Instructor类的equals方法比较的问题

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#70]
注意到Instructor及其父类User中都并未重写Object类当中的equals方法，这样导致使用equals判定getCourseSectionClasses方法的返回结果时，一定要两个Instructor对象地址完全一致才可认为相等，而并非内容（如id和fullname）。请问判定是一定要两个对象的地址完全相同，而非仅仅内容相同即可？

**Comment by NewbieOrange** [comment]
测试时只要内容一样即可。

**Comment by YeeTone** [comment]
> 测试时只要内容一样即可。

请问Major类是否也遵循该判定规则？

**Comment by NewbieOrange** [comment]
所有类都是。
