### ISSUE TITLE
关于已选课程和通过课程的区分

### ISSUE THREAD

**Issue by Antoniano1963** [NewbieOrange/SUSTech-SQL-Project2-Public#73]
1 通过课程可以认为是老师已经给分且为P或者分数大于等于60的课程吗？
2 已选课程可以认为是老师没有给分的课程吗？
3 因为searchcourse方法中semesterID这个参数是一定给的，所以处理时认为开课学期和给定semester相同且没有分数的认为是学生这学期选的课。但是在处理enrollCourse方法是发现这个没有给定学期，请问是直接像2那样理解已选课程忽略学期，还是讲要选定的课程学期拿出来，然后像searchcourse那样根据学期和没有分数认定这门课是学生已经选了但没有通过的。因为课程冲突类型涉及到返回result时是ALREADY_ENROLLED,还是ALREADY_PASSED,的区别

**Comment by NewbieOrange** [comment]
> 通过课程可以认为是老师已经给分且为P或者分数大于等于60的课程吗？

Yes.

> 已选课程可以认为是老师没有给分的课程吗？

Yes, either have score or not.

> 因为searchcourse方法中semesterID这个参数是一定给的，所以处理时认为开课学期和给定semester相同且没有分数的认为是学生这学期选的课。但是在处理enrollCourse方法是发现这个没有给定学期，请问是直接像2那样理解已选课程忽略学期，还是讲要选定的课程学期拿出来，然后像searchcourse那样根据学期和没有分数认定这门课是学生已经选了但没有通过的。因为课程冲突类型涉及到返回result时是ALREADY_ENROLLED,还是ALREADY_PASSED,的区别

You misunderstood `ALREADY_ENROLLED` and `ALREADY_PASSED`, please read the document again.

**Comment by Antoniano1963** [comment]
The course section is already enrolled by the student
The course (of the section) is already passed by the student
文档里是这么说的，请问我理解的ALREADY_PASSED和ALREADY_ENROLLED具体那里有问题呀，不是一个是通过的，就是1那么理解，一个是已经注册的吗？
既然2是对的，那么已经注册的课程就是所有没有分数的课程？请问那个either have score or not是怎么理解，得分就是过或者没过，不得分就是enrolled的？

**Comment by NewbieOrange** [comment]
> The course section is already enrolled by the student

The **section** is already enrolled, there is nothing to do with semester here.

> The course (of the section) is already passed by the student

The document did not mension semester here too.

> 请问那个either have score or not是怎么理解，得分就是过或者没过，不得分就是enrolled的

Either the student have score or not, he (or she) is **enrolled**. If the score is given and >= (or <) than 60, then it is passed or failed.

**Comment by Antoniano1963** [comment]
好的，谢谢老师
