### ISSUE TITLE
About foreign key deletion on deleting some row

### ISSUE THREAD

**Issue by Liu-rj** [NewbieOrange/SUSTech-SQL-Project2-Public#74]
I'm confusing about deleting method. When deleting a row in some tables such as department, should other rows in other tables that have foreign key pointing to this department, for example, majors, be deleted meanwhile? I've already been doing so as what happens in reality.

**Comment by NewbieOrange** [comment]
We define our delete*() as delete cascade, so you should delete all rows containing non-nullable foreign key reference to the deleted row.
