### ISSUE TITLE
About the `ignoreConflict` parameter in the method `searchCourse`

### ISSUE THREAD

**Issue by Camsyn** [NewbieOrange/SUSTech-SQL-Project2-Public#75]
`ignoreConflict - whether or not to ignore course or time conflicting course sections. Note that a section is both course and time conflicting with itself.`
Q1: If ignoreConflict = false, does it mean that to filter out **those course sections in this semester** (indicated by `semesterId`) having **conflicts with** the **course sections the specific student  (indicated by `studentId`)  enrolling in**?

Q2: If Q1 is true,  whether or not the courseConflict covers previous enrolled courses? **In other words, is `courseConflict` relevant to semester?**  For example, if student A enrolled and passed a course B in semester 1, then can A search a course section b belonging to course B in semester 2? And what about the student A fail the course B?

In addition,
Q3: `ignoreMissingPrerequisites : whether or not to ignore courses with missing prerequisites.`
 What is the meaning of `missing prerequisite`? The courses with **null** preresquisite?  The courses with prerequisite unmatching with the specific student?

**Comment by NewbieOrange** [comment]
Filter out when `ignoreConflict` is `true` instead of `false`.

> does it mean that to filter out those course sections in this semester (indicated by semesterId) having conflicts with the course sections the specific student (indicated by studentId) enrolling in

Yes.

> is courseConflict relevant to semester?

Yes.

> What is the meaning of missing prerequisite?

The student hasn't pass all the prerequisites of that course.

**Comment by Camsyn** [comment]
But in my consideration, `ignoreConflict`  = true means I should ignore the conflicts, i.e. **do not figure out** the conflicted courses

**Comment by NewbieOrange** [comment]
`ignoreConflict` = `true` means the **results** should ignore the conflicting courses.
