### ISSUE TITLE
Question about courseSectionClass

### ISSUE THREAD

**Issue by Brooklyn-0** [NewbieOrange/SUSTech-SQL-Project2-Public#80]
from the issue, it says that a section can have (almost) infinite amount of classes. However, another question before also say that in many cases, you may treat a “course section” as a pair of “course section class” (i.e. the lecture and the lab), so choose one course section means you are already in both the course section class. 
Does it mean that a section can have infinite classes, and when a student choose this section, he is enrolled in all of the classes of it instead of having the freedom to choose some classes below it, which will affect how we judge the time schedule.

**Comment by NewbieOrange** [comment]
> Does it mean that a section can have infinite classes, and when a student choose this section, he is enrolled in all of the classes of it instead of having the freedom to choose some classes below it, which will affect how we judge the time schedule.

Yes.
