### ISSUE TITLE
Question about page index and page size

### ISSUE THREAD

**Issue by Brooklyn-0** [NewbieOrange/SUSTech-SQL-Project2-Public#81]
page index和page size具体在searchCourse里是什么意思呀，没怎么看懂它的作用。是指返回的courseSearchEntry的限制大小么（就是指不是所有的结果都返回，而是限制了返回多少）？那这样子的话page index是干什么用的？

**Comment by NewbieOrange** [comment]
page index是值页码（每页有page size个entry，你应该返回第page index页（从0计数））。
