### ISSUE TITLE
学生成功选了一个section，老师给了一个不及格分之后，学生再一次enrollcourse这个section，enrollResult是什么

### ISSUE THREAD

**Issue by deepoceansame** [NewbieOrange/SUSTech-SQL-Project2-Public#85]

**Comment by NewbieOrange** [comment]
一个section对应着一个学期，那给分之后再选肯定是返回ALREADY_ENROLLED.

**Comment by Zhou-Yicheng** [comment]
SUCCESS

**Comment by Zhou-Yicheng** [comment]
> 一个section对应着一个学期，那给分之后再选肯定是返回ALREADY_ENROLLED.

同学的意思应该是挂科重修，应该返回SUCCESS

**Comment by NewbieOrange** [comment]
> 同学的意思应该是挂科重修，应该返回SUCCESS

怎么可能选上一个学期的课重修？

**Comment by Zhou-Yicheng** [comment]
> 怎么可能选上一个学期的课重修？

哦哦 那应该是不存在这种情况
