### ISSUE TITLE
关于测试脚本的答案问题

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#86]
测试脚本可以通过System.out输出流输出一些答案，请问测试脚本如果全部通过的话具体的答案是多少呢？

**Comment by Zhou-Yicheng** [comment]
[sampleResult.txt](https://github.com/NewbieOrange/SUSTech-SQL-Project2-Public/blob/3ba795db5df476c4813ca0bf168bf82c94828814/data/sampleResult.txt)

**Comment by YeeTone** [comment]
找到了，谢谢：）
