### ISSUE TITLE
有关testCourseTables数据的疑问

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#87]
在testCourseTables的第55个测试用例中，要获取11712941在2019-01-26的courseTable,所给sampleResult中该学生在周一需要上计算机程序设计基础A[中英双语2班-实验11班]，但是在所给数据中，该学期开始为2019-02-01(周五，未从周一开始)，学期开始在在2019-01-26之后，11712941在2019-01-26当周课表应该为空，这个测试用例是否有误？

**Comment by NewbieOrange** [comment]
是的，稍后修正。

**Comment by NewbieOrange** [comment]
已修正，请更新最新数据。
