### ISSUE TITLE
数据库编码影响结果排序顺序

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#88]
在testSearchCourses1的第133个case中，expected第0项courseid为CS102A,fullName为计算机程序设计基础A[中英双语1班-实验5班],第5项courid为CS102A，fullName为计算机程序设计基础A[英文班-实验3班]，但是按照文档要求，应该以courseid为第一关键字，fullName为第二关键字排序，这两项courseid相同，但第五项的fullName字典序小于第0项，按文档要求应是第五项排在前面
，此处数据是否有误？

**Comment by NewbieOrange** [comment]
![图片](https://user-images.githubusercontent.com/7200314/120754181-e248d400-c53e-11eb-8045-b8e991688878.png)

不是"中英" < "英文" 吗？

**Comment by dengsh12** [comment]
> ![图片](https://user-images.githubusercontent.com/7200314/120754181-e248d400-c53e-11eb-8045-b8e991688878.png)
> 
> 不是"中英" < "英文" 吗？

![image](https://user-images.githubusercontent.com/62536982/120754550-656a2a00-c53f-11eb-94e3-562db51e8bb0.png)
wo'zhe'l可是我这里英文小于中英诶  是啥原因啊

**Comment by NewbieOrange** [comment]
![图片](https://user-images.githubusercontent.com/7200314/120756566-fb9f4f80-c541-11eb-8c32-9419aa6acae9.png)

**Comment by dengsh12** [comment]
解决了  是编码的问题，感谢

**Comment by NewbieOrange** [comment]
> 
> 
> 解决了 是编码的问题，感谢

是需要用UTF-8吗？

**Comment by dengsh12** [comment]
> > 解决了 是编码的问题，感谢
> 
> 是需要用UTF-8吗？
是的

**Comment by NewbieOrange** [comment]
创建符合需求的数据库的方法：

![图片](https://user-images.githubusercontent.com/7200314/121348343-d3a55700-c95a-11eb-9642-b0cde60bf9b5.png)

直接执行即可（红色提示没关系）。
