### ISSUE TITLE
有关searchcourse数据的疑问 2

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#92]
在testsearchcourse1的第301个case中，pagesize=10,pageind=28（参数如下图）,expected中结果的size为5，但是插入数据的json中仅有196个coursesection,该方法至少需要忽略10*28=280个满足条件的section,196比280还差许多，该处数据是否有误？
![image](https://user-images.githubusercontent.com/62536982/120775209-93f2ff80-c555-11eb-90b6-17c76aa99ced.png)

**Comment by dengsh12** [comment]
![image](https://user-images.githubusercontent.com/62536982/120783144-4f6b6200-c55d-11eb-8a04-114ffcc766c4.png)

**Comment by NewbieOrange** [comment]
pageIndex参数传错了，修复中。

**Comment by NewbieOrange** [comment]
已修正，请检查。需要注意新数据比较多，可能运行较慢。
