### ISSUE TITLE
关于CourseSectionClass的问题

### ISSUE THREAD

**Issue by sdww0** [NewbieOrange/SUSTech-SQL-Project2-Public#93]
这个类里面的老师是单独一个，但是在导数据的时候发现这方面有冲突的数据，老师不同，其他相同，这种需要插入吗

**Comment by NewbieOrange** [comment]
> 
> 
> 这个类里面的老师是单独一个，但是在导数据的时候发现这方面有冲突的数据，老师不同，其他相同，这种需要插入吗

按照框架传入的数据导入即可。
