### ISSUE TITLE
searchName in searchCourse

### ISSUE THREAD

**Issue by JMZ-kk** [NewbieOrange/SUSTech-SQL-Project2-Public#95]
According to your prompt int the StudentService, the format of the parameter searchName in searchCourse should be course.name[section.name]. However, we find 矿物 in the one row of the test case in the position of this parameter. It is controversial.

**Comment by NewbieOrange** [comment]
In no where does the document say the search course will be in that format.

**Comment by JMZ-kk** [comment]
In fact, it is. There is one line in the introduction of method searchCourse:
* @param searchName                 search course name. Rule: searchName in "course.name[section.name]"

**Comment by NewbieOrange** [comment]
You are not interpreting it correctly. It says the matching rule is searchName in "...", not searchName is "...."
