### ISSUE TITLE
有关Test enroll course 2数据的疑问

### ISSUE THREAD

**Issue by dengsh12** [NewbieOrange/SUSTech-SQL-Project2-Public#96]
在Test enroll course 2的第32个测试用例中，学号为11716737的学生尝试选择CS102A的英文班-实验2班，但是该学生已经选择过该班，COURSE_CONFLICT_FOUND和ALREADY_ENROLLED同时发生，按照文档里的顺序应该优先返回ALREADY_ENROLLED，但是expected为COURSE_CONFLICT_FOUND，该处数据是否有误？

**Comment by NewbieOrange** [comment]
`ALREADY_ENROLLED` 定义中仅限为同一`section`，此处是同一`course`，故返回`COURSE_CONFLICT_FOUND`。
