### ISSUE TITLE
关于searchCourse的测试数据的问题

### ISSUE THREAD

**Issue by YeeTone** [NewbieOrange/SUSTech-SQL-Project2-Public#97]
考虑searchCourse的第一个测试数据。请问为什么第4个元素是有机化学II（courseID：CH206）而不是courseID字典序更小的化学原理实验A（courseID：CH102-17）？
![QQ截图20210604202716](https://user-images.githubusercontent.com/64548919/120801433-bac02e80-c573-11eb-80ca-79bd2fe981b5.png)
![QQ截图20210604203106](https://user-images.githubusercontent.com/64548919/120801498-d1668580-c573-11eb-9fc0-b31e7522393a.png)

**Comment by NewbieOrange** [comment]
因为结果里根本就不应该有CH102-17吧，请检查是否正确实现了四个ignore参数。

**Comment by YeeTone** [comment]
但是事实上第一个测试用例里面，4个ignore的参数均为true，也就意味着可以不考虑4个ignore的相关因素对结果集的筛选。因此CH102-17是不是应该是符合要求的？
![QQ截图20210604223621](https://user-images.githubusercontent.com/64548919/120818794-85bcd780-c585-11eb-8215-864172d014aa.png)

**Comment by NewbieOrange** [comment]
ignore是true代表你要ignore，你理解反了。

**Comment by YeeTone** [comment]
啊，原来ignore是说这个意思（捂脸），感谢~
