### ISSUE TITLE
关于getEnrolledCoursesAndGrades的疑问

### ISSUE THREAD

**Issue by 1371131436** [NewbieOrange/SUSTech-SQL-Project2-Public#98]
注释里说，当某一学期该课挂掉，下学期又上了同一门课时，记录最新的成绩，但入参有SemesterID，当入参的SemesterID为挂掉了这门课的学期时，Map<Course, Grade> 该记录更新后的成绩还是挂掉的成绩？

**Comment by NewbieOrange** [comment]
挂掉的成绩（即入参学期的成绩）。
